import { LitElement } from "lit";
import { Option } from "./../models";
export declare class SelectPure extends LitElement {
    static get styles(): import("lit").CSSResultGroup;
    options: Option[];
    visible: boolean;
    selectedOption: Option;
    _selectedOptions: Option[];
    disabled: boolean;
    multiple: boolean;
    name: string;
    _id: string;
    formName: string;
    value: string;
    values: string[];
    defaultLabel: string;
    private nativeSelect;
    private form;
    private hiddenInput;
    constructor();
    firstUpdated(): void;
    open(): void;
    close(): void;
    enable(): void;
    disable(): void;
    get selectedIndex(): number | undefined;
    set selectedIndex(index: number | undefined);
    get selectedOptions(): HTMLCollectionOf<HTMLOptionElement> | undefined;
    private processForm;
    private handleNativeSelectChange;
    private processOptions;
    private onSelect;
    private selectOption;
    private afterSelect;
    private handleKeyPress;
    private onCrossClick;
    private renderNativeOptions;
    private renderLabel;
    render(): import("lit-html").TemplateResult<1>;
}
//# sourceMappingURL=Select.d.ts.map